version: '3.8'

services:
  frontend:
    image: funcid/oppenganger-frontend:latest
    restart: always
    ports:
      - '3000:3000'
    networks:
      - bridge

  engine:
    image: funcid/oppelganger:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      S3_ENDPOINT_URL: http://minio:9000
      S3_BUCKET_VIDEOS: videos-bucket
      S3_BUCKET_PERSONALITIES: personalities-bucket
      S3_REGION_NAME: us-east-1
      S3_ACCESS_KEY_ID: root
      S3_SECRET_ACCESS_KEY: password0
    networks:
      - bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, video]

  minio:
    user: root
    image: bitnami/minio:latest
    volumes:
      - /path/to/minio-persistence:/bitnami/minio/data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      BITNAMI_DEBUG: true
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password0
      MINIO_DEFAULT_BUCKETS: videos-bucket,personalities-bucket
    restart: unless-stopped
    networks:
      - bridge

networks:
  bridge:
    driver: bridge